server:
  port: 10010
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      port: 8500 #指定注册中心端口，默认为8500
      host: localhost #指定注册中心IP地址
      discovery:
        serviceName: gateway-service
        locator:
          lower-case-service-id: true
          enabled: true
        register: true
        prefer-ip-address: true #这个必须配
        tags: version=1.0
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        healthCheckInterval: 15s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #用户中心
        - id: sys-service
          uri: lb://sys-service
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
        # 认证中心
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true