server:
  port: 8081
spring:
  application:
    name: sys-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nc_sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 972915
  cloud:
    consul:
      port: 8500 #指定注册中心端口，默认为8500
      host: 127.0.0.1 #指定注册中心IP地址
      discovery:
        serviceName: sys-service
        locator:
          lower-case-service-id: true
          enabled: true
        register: true
        prefer-ip-address: true #这个必须配
        tags: version=1.2
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        healthCheckInterval: 15s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
logging:
  level:
    com.itheima: debug
